# Generated by Django 3.2 on 2021-11-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descricao',
            new_name='descricacao',
        ),
    ]
